### PR TITLE
fixed problem with count of interrupts stat

### PR DESCRIPTION
**Pull request by yuri-zubov**
hello guys!

It's PR fixes the issue https://github.com/sensu-plugins/sensu-plugins-cpu-checks/issues/19.
I saw structure of file and decided that we need to take first element of array for all metrics
```
cpu  1137648 2216 211921 6665259 173726 0 20076 0 0 0
cpu0 304759 470 55044 1660435 34924 0 4692 0 0 0
cpu1 288575 509 53598 1671356 32795 0 7355 0 0 0
cpu2 258225 563 50921 1674970 50697 0 4750 0 0 0
cpu3 286088 673 52357 1658496 55308 0 3278 0 0 0
intr 32388174 23 22 0 0 0 0 0 0 1 3515970 0 0 221 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 488884 22 418588 1028146 6689149 33 35 1012 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 82974757
btime 1516007665
processes 47179
procs_running 1
procs_blocked 0
softirq 31175665 7947760 7626420 3442 1045959 414381 0 34751 7253419 0 6849533

### CODE REVIEW

**Comment by majormoses** [comment]
@yuri-zubov Thanks for taking a look at this and proposing a solution.

What platform are you on? I would like to check to see if we have problems on various platforms as the original issue indicated that the file contents might defer on various platforms. I could be misunderstanding and was intended as how they categorize and calculate interrupts differs.

> The last column is just the total for a given interrupt (which can actually vary between platform).

**Comment by yuri-zubov** [comment]
@majormoses I use Ubuntu 16.04 LTS

**Comment by majormoses** [comment]
Thanks for the info I will take a look at this tonight.

**Comment by majormoses** [comment]
Looks good to me, I verified this on Ubuntu and Centos. If this breaks other platforms we will deal with it then.

**Review by majormoses — APPROVED** [review]
LGTM as it was simple and I was aware of how the change worked I added a [changelog entry](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md). Thanks for getting this through.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-cpu-checks/versions/1.1.3

**Comment by yuri-zubov** [comment]
thank you

**Pull request merged**
